#pragma once

enum ofxGAxisType {
	GRAFICA_X_AXIS, GRAFICA_Y_AXIS, GRAFICA_TOP_AXIS, GRAFICA_RIGHT_AXIS
};

enum ofxGTextAlignment {
	GRAFICA_CENTER_ALIGN, GRAFICA_LEFT_ALIGN, GRAFICA_RIGHT_ALIGN
};

enum ofxGGridDirection {
	GRAFICA_HORIZONTAL_DIRECTION,
	GRAFICA_VERTICAL_DIRECTION,
	GRAFICA_BOTH_DIRECTIONS
};
